version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - exhaustive
#   - goconst --- Disabled because it produces too many false positives, e.g. for HTTP header names and values.
    - gocritic
    - gocyclo
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nilnil
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    lll:
      line-length: 250
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - \.cache/
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - \.cache/
