version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - exhaustive
    - gocritic
    - gomodguard
    - gosec
    - lll
    - makezero
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - unparam
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - \.cache/
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - \.cache/
